# Generated by Django 5.1.1 on 2024-09-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=64, verbose_name='Id чата в телеге')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('gender', models.CharField(blank=True, max_length=16, null=True, verbose_name='Гендер')),
                ('category', models.CharField(blank=True, max_length=32, null=True, verbose_name='Для чего в боте')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Аватарка пользователя')),
                ('check_photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото для проверки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание о себе')),
                ('find_age', models.CharField(blank=True, max_length=8, null=True, verbose_name='Какой возраст предпочитает')),
                ('find_gender', models.CharField(blank=True, max_length=16, null=True, verbose_name='Какой гендер ищет')),
                ('active', models.BooleanField(default=True, verbose_name='Активен ли поиск')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Проеверен ли аккаунт')),
                ('is_ban', models.BooleanField(default=False, verbose_name='В бане ли аккаунт')),
            ],
        ),
    ]
