# Generated by Django 5.1.1 on 2024-09-21 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='users',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 1, 5, 48, 237567), verbose_name='Время последней активности'),
        ),
    ]
