# Generated by Django 5.1.1 on 2024-09-22 17:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_users_alter_user_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 20, 45, 41, 642674), verbose_name='Время последней активности'),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64, verbose_name='Тип симпатии')),
                ('have_answer', models.BooleanField(default=False, verbose_name='Есть ли взаимность')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Дата симпатии')),
                ('form_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_status', to='users.user', verbose_name='Человек, который поставил лайк/дизлайк/жалобу')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_status', to='users.user', verbose_name='Человек, которому поставили лайк/дизлайк/жалобу')),
            ],
        ),
    ]
